software-mirror=https://raw.githubusercontent.com/acth2/cydramanager-db/refs/heads/main/softwares
#take: url
#default: TODO

update-archive-db=https://github.com/acth2/cydramanager-db/releases/download/13.0/versions.tar.gz
#take: url
#default: TODO

update-archive-db-instruc=https://github.com/acth2/cydramanager-db/releases/download/13.0/instructions.tar.gz
#take: url
#default: 

tmp-folder=/tmp/cydramanager.tmp
#take: path
#default: /tmp/cydramanager.tmp

parallel-jobs=auto
#take: int
#default: auto

dependency-handling=install
#default: install
#options: ignore, install

default-arg=
#take: arguments separated by spaces
#default: 
